import PDFDocument from 'pdfkit';
import type { Readable } from 'stream';

interface EntrepreneurReportData {
  user: {
    firstName: string; lastName: string; email: string;
    phone: string | null; county: string | null;
    businessName: string | null; businessStage: string | null;
    businessDescription: string | null; createdAt: Date;
  };
  applications: Array<{ id: number; status: string; program: { name: string }; appliedAt: Date }>;
  smartGoal:     { goalStatement: string; specific: string; measurable: string; achievable: string; relevant: string; timebound: string; adminComment: string | null } | null;
  milestonePlan: { businessName: string; grantAmount: string | null; milestones: unknown } | null;
  marketResearch: { businessName: string; surveyObjective: string | null; topChallenges: unknown } | null;
  evidence:       Array<{ fileName: string; status: string; category: string | null }>;
  businessPlan:   { planData: unknown } | null;
}

interface ProgramReportData {
  program: { id: number; name: string; description: string | null; status: string; createdAt: Date };
  totalApplications: number;
  approved: number;
  rejected: number;
  pending: number;
  underReview: number;
}

function addHeader(doc: PDFKit.PDFDocument, title: string) {
  doc.rect(0, 0, doc.page.width, 60).fill('#16a34a');
  doc.fillColor('#ffffff').fontSize(20).font('Helvetica-Bold').text('FLAREHUB', 40, 18);
  doc.fontSize(10).font('Helvetica').text(title, 40, 42);
  doc.fillColor('#000000');
  doc.moveDown(4);
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.moveDown(0.5);
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#16a34a').text(title);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor('#16a34a').lineWidth(1).stroke();
  doc.fillColor('#000000').fontSize(10).font('Helvetica');
  doc.moveDown(0.5);
}

function row(doc: PDFKit.PDFDocument, label: string, value: string | null | undefined) {
  if (!value) return;
  doc.font('Helvetica-Bold').text(`${label}: `, { continued: true }).font('Helvetica').text(value);
}

export function generateEntrepreneurReport(data: EntrepreneurReportData): Readable {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  const fullName = `${data.user.firstName} ${data.user.lastName}`;

  addHeader(doc, 'Entrepreneur Profile Report');

  sectionTitle(doc, 'Personal Information');
  row(doc, 'Name',     fullName);
  row(doc, 'Email',    data.user.email);
  row(doc, 'Phone',    data.user.phone);
  row(doc, 'County',   data.user.county);
  row(doc, 'Joined',   data.user.createdAt.toLocaleDateString('en-KE'));

  sectionTitle(doc, 'Business Information');
  row(doc, 'Business Name',  data.user.businessName);
  row(doc, 'Stage',          data.user.businessStage);
  row(doc, 'Description',    data.user.businessDescription);

  sectionTitle(doc, 'Applications');
  if (data.applications.length === 0) {
    doc.text('No applications.');
  } else {
    for (const app of data.applications) {
      doc.text(`• ${app.program.name} — ${app.status} (${app.appliedAt.toLocaleDateString('en-KE')})`);
    }
  }

  if (data.smartGoal) {
    sectionTitle(doc, 'SMART Goals');
    row(doc, 'Goal',       data.smartGoal.goalStatement);
    row(doc, 'Specific',   data.smartGoal.specific);
    row(doc, 'Measurable', data.smartGoal.measurable);
    row(doc, 'Achievable', data.smartGoal.achievable);
    row(doc, 'Relevant',   data.smartGoal.relevant);
    row(doc, 'Timebound',  data.smartGoal.timebound);
    if (data.smartGoal.adminComment) row(doc, 'Admin Comment', data.smartGoal.adminComment);
  }

  if (data.milestonePlan) {
    sectionTitle(doc, 'Milestone Plan');
    row(doc, 'Business', data.milestonePlan.businessName);
    row(doc, 'Grant',    data.milestonePlan.grantAmount);
  }

  if (data.marketResearch) {
    sectionTitle(doc, 'Market Research');
    row(doc, 'Business',  data.marketResearch.businessName);
    row(doc, 'Objective', data.marketResearch.surveyObjective);
  }

  sectionTitle(doc, 'Evidence Summary');
  const evByStatus = data.evidence.reduce<Record<string, number>>((acc, e) => {
    acc[e.status] = (acc[e.status] ?? 0) + 1;
    return acc;
  }, {});
  doc.text(`Total: ${data.evidence.length} files`);
  for (const [status, count] of Object.entries(evByStatus)) {
    doc.text(`  ${status}: ${count}`);
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#6b7280')
    .text(`Generated by Flarehub on ${new Date().toLocaleString('en-KE')}`, { align: 'center' });

  doc.end();
  return doc as unknown as Readable;
}

export function generateProgramReport(data: ProgramReportData): Readable {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  addHeader(doc, 'Program Summary Report');

  sectionTitle(doc, 'Program Details');
  row(doc, 'Name',    data.program.name);
  row(doc, 'Status',  data.program.status);
  row(doc, 'Created', data.program.createdAt.toLocaleDateString('en-KE'));
  if (data.program.description) row(doc, 'Description', data.program.description);

  sectionTitle(doc, 'Application Statistics');
  doc.text(`Total Applications: ${data.totalApplications}`);
  doc.text(`Approved:          ${data.approved}`);
  doc.text(`Rejected:          ${data.rejected}`);
  doc.text(`Under Review:      ${data.underReview}`);
  doc.text(`Pending:           ${data.pending}`);

  if (data.totalApplications > 0) {
    const rate = Math.round((data.approved / data.totalApplications) * 1000) / 10;
    doc.moveDown(0.5).font('Helvetica-Bold').text(`Success Rate: ${rate}%`).font('Helvetica');
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#6b7280')
    .text(`Generated by Flarehub on ${new Date().toLocaleString('en-KE')}`, { align: 'center' });

  doc.end();
  return doc as unknown as Readable;
}
